apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: golang-starter
  title: Golang Microservice
  description: Create a Golang repo with this template built by members of the Go community
  tags:
    - experimental
    - go
spec:
  owner: sulanta.leisangthem@sophos.com
  parameters:
    required:
      - component_id
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
steps:
  - id: template
    name: Fetch Skeleton + Template


